source("toolkit/R/runtime.R")
source("toolkit/R/figure_style.R")
out <- file.path("test-output", "figure-style")
dir.create(out, recursive = TRUE, showWarnings = FALSE)
config <- list(output = list(figure_format = "png"), figure_style = list(colors = list(condition = list(control = "#4477AA", pah = "#D55E00"))))
config$metadata <- list(sample = "sample_label", condition = "condition")
a <- paper_colors(c("0", "1", "2", "0"), "cluster", config, out)
b <- paper_colors(c("2", "0"), "cluster", config, out)
stopifnot(identical(unname(a[c("0", "2")]), unname(b[c("0", "2")])))
stopifnot(identical(paper_colors("control", "condition", config, out)[[1]], "#4477AA"))
stopifnot(length(unique(a)) == 3L)
stopifnot(identical(paper_formats(list()), "png"))
stopifnot(identical(paper_formats(list(output = list(figure_format = "both"))), c("png", "pdf")))
obj <- readRDS("tests/fixtures/tiny_scrna.rds")
counts <- SeuratObject::LayerData(obj, assay = "RNA", layer = "counts")
extra <- counts
rownames(extra) <- paste0("synthetic_", rownames(extra))
expanded <- Seurat::CreateSeuratObject(rbind(counts, extra), meta.data = obj[[]])
expanded[["umap"]] <- obj[["umap"]]
obj <- expanded
obj <- Seurat::NormalizeData(obj, verbose = FALSE)
original <- obj
files <- paper_dimplot(obj, "umap", c("seurat_clusters", "sample_label", "condition"), file.path(out, "umap_preview"), config, out, point_size = .8)
genes <- head(rownames(obj), 35)
files <- c(files, paper_dotplot(obj, genes, "RNA", "seurat_clusters", file.path(out, "dotplot_preview"), config, out))
config$figure_style$feature_genes <- c(head(rownames(obj), 7), "not_a_real_gene")
files <- c(files, paper_features(obj, "umap", config, out))
stopifnot(all(file.exists(files)), length(files) == 5L, identical(obj, original))
record <- utils::read.delim(file.path(out, "_provenance/figure_status.tsv"))
stopifnot(any(record$status == "skipped"), all(record$style_version == "paper_v1"))
cat("PASS stable colours, formats, UMAP, paginated dotplots/FeaturePlots, missing genes and unchanged object\n")
