source("toolkit/R/runtime.R")
out <- tempfile("layout-")
dir.create(out)
config_path <- file.path(out, "config.json")
writeLines('{"project":{"id":"layout_test"}}', config_path)
config <- read_skill_config(config_path)
table_path <- file.path(out, "results.tsv")
writeLines("gene\tvalue\nA\t1", table_path)
log_path <- technical_path(out, "run.log")
writeLines("START", log_path)
manifest_path <- technical_path(out, "run_manifest.json")
writeLines("old manifest", manifest_path)
write_run_manifest(config, "test", out, c(table_path, log_path, manifest_path))
record <- jsonlite::read_json(manifest_path, simplifyVector = FALSE)
stopifnot(!file.exists(file.path(out, "run_manifest.json")))
stopifnot(length(record$artifacts) == 2L)
stopifnot(identical(record$artifacts[[1]]$sha256, .scrna_sha256(table_path)))
stopifnot(isTRUE(record$artifacts[[2]]$mutable), is.null(record$artifacts[[2]]$sha256))
cat("EXIT 0\n", file = log_path, append = TRUE)
stopifnot(identical(record$artifacts[[1]]$sha256, .scrna_sha256(table_path)))
unlink(out, recursive = TRUE)
cat("PASS technical paths and mutable-log provenance\n")
