args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1L) stop("Usage: Rscript analyze_subset.R config.json")
script_file <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]); source(file.path(dirname(normalizePath(script_file)), "runtime.R"))
config <- read_skill_config(args[[1]])
if (!requireNamespace("Seurat", quietly = TRUE)) stop("Package 'Seurat' is required")
obj <- load_scrna_object(cfg_get(config, "input.object", required = TRUE), "auto")
sample_col <- cfg_get(config, "metadata.sample", required = TRUE); type_col <- cfg_get(config, "metadata.cell_type", required = TRUE)
assert_metadata(obj, c(sample_col, type_col)); include <- unlist(cfg_get(config, "subset.include", required = TRUE))
keep <- rownames(obj[[]])[obj[[]][[type_col]] %in% include]
if (!length(keep)) stop("Subset selection matched zero cells")
sub <- subset(obj, cells = keep)
out <- prepare_output(config); meta_path <- file.path(out, "subset_metadata.tsv"); count_path <- file.path(out, "subset_counts.mtx"); object_path <- file.path(out, "subset_object.qs"); summary_path <- file.path(out, "subset_summary.tsv")
utils::write.table(cbind(cell_id = rownames(sub[[]]), sub[[]]), meta_path, sep = "\t", quote = FALSE, row.names = FALSE)
counts <- get_raw_counts(sub)
if (!requireNamespace("Matrix", quietly = TRUE)) stop("Package 'Matrix' is required")
Matrix::writeMM(counts, count_path); utils::write.table(rownames(counts), file.path(out, "features.tsv"), quote = FALSE, row.names = FALSE, col.names = FALSE); utils::write.table(colnames(counts), file.path(out, "barcodes.tsv"), quote = FALSE, row.names = FALSE, col.names = FALSE)
save_scrna_object(sub, object_path)
summary <- as.data.frame(table(sample = sub[[]][[sample_col]], selected_label = sub[[]][[type_col]])); utils::write.table(summary, summary_path, sep = "\t", quote = FALSE, row.names = FALSE)
write_run_manifest(config, "09-scrna-export-subset", out, c(object_path, count_path, meta_path, summary_path, file.path(out, "features.tsv"), file.path(out, "barcodes.tsv")), "Parent object was not modified")
