args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1L) stop("Usage: Rscript annotate_cells.R config.json")
script_file <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]); source(file.path(dirname(normalizePath(script_file)), "runtime.R"))
config <- read_skill_config(args[[1]])
if (!requireNamespace("Seurat", quietly = TRUE)) stop("Package 'Seurat' is required")
obj <- load_scrna_object(cfg_get(config, "input.object", required = TRUE), "auto")
sample_col <- cfg_get(config, "metadata.sample", required = TRUE); assert_metadata(obj, sample_col)
dims <- unlist(cfg_get(config, "clustering.dims", as.list(1:30))); resolution <- cfg_get(config, "clustering.resolution", 0.5)
if (!"pca" %in% names(obj@reductions)) obj <- Seurat::NormalizeData(obj, verbose = FALSE) |> Seurat::FindVariableFeatures(verbose = FALSE) |> Seurat::ScaleData(verbose = FALSE) |> Seurat::RunPCA(verbose = FALSE)
obj <- Seurat::FindNeighbors(obj, dims = dims, verbose = FALSE) |> Seurat::FindClusters(resolution = resolution, verbose = FALSE)
if (!"umap" %in% names(obj@reductions)) obj <- Seurat::RunUMAP(obj, dims = dims, verbose = FALSE)
markers <- Seurat::FindAllMarkers(obj, only.pos = TRUE, logfc.threshold = cfg_get(config, "markers.logfc_threshold", 0.25), min.pct = cfg_get(config, "markers.min_pct", 0.1))
clusters <- sort(unique(as.character(Seurat::Idents(obj))))
review <- data.frame(cluster = clusters, candidate_broad = "", candidate_fine = "", positive_markers = "", negative_markers = "", confidence = "", decision = "", notes = "")
out <- prepare_output(config); marker_path <- file.path(out, "cluster_markers.tsv"); review_path <- file.path(out, "annotation_review.tsv"); object_path <- file.path(out, "clustered_object.qs")
utils::write.table(markers, marker_path, sep = "\t", quote = FALSE, row.names = FALSE); utils::write.table(review, review_path, sep = "\t", quote = FALSE, row.names = FALSE); save_scrna_object(obj, object_path)
write_run_manifest(config, "annotate-scrna-cells", out, c(marker_path, review_path, object_path), "Formal labels were not written")
