args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1L) stop("Usage: Rscript differential_analysis.R config.json")
script_file <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]); source(file.path(dirname(normalizePath(script_file)), "runtime.R"))
config <- read_skill_config(args[[1]])
if (!requireNamespace("Seurat", quietly = TRUE)) stop("Package 'Seurat' is required")
obj <- load_scrna_object(cfg_get(config, "input.object", required = TRUE), "auto")
sample_col <- cfg_get(config, "metadata.sample", required = TRUE); condition_col <- cfg_get(config, "metadata.condition", required = TRUE)
assert_metadata(obj, c(sample_col, condition_col)); numerator <- cfg_get(config, "comparison.numerator", required = TRUE); denominator <- cfg_get(config, "comparison.denominator", required = TRUE)
meta <- obj[[]]; design <- unique(meta[c(sample_col, condition_col)]); design <- design[design[[condition_col]] %in% c(numerator, denominator), , drop = FALSE]
sample_condition_counts <- table(design[[condition_col]])
out <- prepare_output(config); audit_path <- file.path(out, "design_audit.tsv"); counts_path <- file.path(out, "sample_cell_counts.tsv")
utils::write.table(data.frame(condition = names(sample_condition_counts), biological_samples = as.integer(sample_condition_counts)), audit_path, sep = "\t", quote = FALSE, row.names = FALSE)
cell_counts <- as.data.frame(table(sample = meta[[sample_col]], condition = meta[[condition_col]])); utils::write.table(cell_counts, counts_path, sep = "\t", quote = FALSE, row.names = FALSE)
mode <- cfg_get(config, "analysis.mode", "audit")
artifacts <- c(audit_path, counts_path); notes <- character()
if (mode == "pseudobulk") {
  if (length(sample_condition_counts) != 2L || any(sample_condition_counts < 2L)) stop("Formal pseudobulk requires at least two independent samples per compared condition")
  if (!requireNamespace("DESeq2", quietly = TRUE)) stop("Package 'DESeq2' is required for pseudobulk")
  cells <- rownames(meta)[meta[[condition_col]] %in% c(numerator, denominator)]
  sub <- subset(obj, cells = cells); counts <- Seurat::LayerData(sub, assay = Seurat::DefaultAssay(sub), layer = "counts")
  groups <- factor(sub[[]][[sample_col]]); mm <- Matrix::sparse.model.matrix(~ 0 + groups); pb <- counts %*% mm; colnames(pb) <- sub("^groups", "", colnames(pb))
  coldata <- design[match(colnames(pb), design[[sample_col]]), , drop = FALSE]; rownames(coldata) <- coldata[[sample_col]]; coldata[[condition_col]] <- relevel(factor(coldata[[condition_col]]), denominator)
  dds <- DESeq2::DESeqDataSetFromMatrix(round(as.matrix(pb)), coldata, stats::as.formula(paste0("~", condition_col))); dds <- DESeq2::DESeq(dds)
  result <- as.data.frame(DESeq2::results(dds, contrast = c(condition_col, numerator, denominator))); result$gene <- rownames(result)
  result_path <- file.path(out, "pseudobulk_results.tsv"); utils::write.table(result, result_path, sep = "\t", quote = FALSE, row.names = FALSE); artifacts <- c(artifacts, result_path)
} else notes <- c(notes, "Audit mode only; no differential test was run")
write_run_manifest(config, "run-scrna-differential-analysis", out, artifacts, notes)
